### PR TITLE
Fixes #18: Methods are completed on background thread if ConfigureAwait(false) is used

### LINKED ISSUE #18: Methods are completed on background thread if ConfigureAwait(false) is used
We've observed that the background thread may leak to the consuming application. This is especially true in dotnet console applications – like an ordinary unittest project. UI-based platforms like WPF or Xamarin may behave differently but I haven't tested that (yet).

You can find a failing test [in this commit](https://github.com/slashwhy/litedb-async/commit/afe17232e8c0dea98bdbb6743629359b75c1b60e).

### The underlying flow is this:

- application performs an async operation, like an `InsertAsync`, and awaits the result, using `ConfigureAwait(false)` (1)
- litedb-async enqueues a lambda to perform an operation on the background thread
    - this includes a task completion source to return the result to the caller
- the background thread performs the lambda
- the lambda completes the task completion source (2)
- the consuming application returns from its await (1) – without switching back to its initial synchronization context, as dictated by `ConfigureAwait(false)`
- the consuming application disposes the litedb-async
    - the dispose method attempts to cancel the background thread
    - waiting for the background threads completion (by calling `_backgroundThread.Join`) runs into the provided timeout of 5 seconds. One can observe this with a breakpoint on the `tooslow`-variable introduced in [this commit](https://github.com/slashwhy/litedb-async/commit/afe17232e8c0dea98bdbb6743629359b75c1b60e).
    - As a result the background thread has not finished yet
- the consuming application moves on, maybe leaves the method and though the blocking async operation on the background thread
- the lambda (2) completes
- the background threads loop breaks and the thread completes

This essentially is a deadlock on the `backgroundThread.Join` being called from the background thread itself, which is only cancelled by the timeout.

Not using `ConfigureAwait(false)` does indeed fix the issue – but it's pretty common practice to use this configuration, at least in library projects.

### So, what could one do?

1. The consuming application could try to ensure to always dispose from another thread
2. The consuming application could stop using `ConfigureAwait(false)`
3. The completion of the task completion source could run on another thread, e.g. on the thread pool

Solution 1 would require proper handling in the application – thats not too complication but one has to know that. One can add a sentence to the documentation, but, meeh

Solution 2 would kind of go against common practice. It's probably not that easy to refrain from typical development patterns here, so, meeh.

Solution 3 would require a change on the libraries implementation for every operation completing its task completion source to run all waiting operations on a separate thread. Good luck this is a supported framework feature: One can simply pass `TaskCreationOptions.RunContinuationsAsynchronously` to the task completion sources constructor.

I would totally prefer solution 3 as it's the one with the least headaches and doesn't require special treatment from the application developer. But it's kind of a breaking change.
What do you thing? I'm willing to provide a pull request changing all the `TaskCompletionSource<>` calls appropriately.

### PR DESCRIPTION
**Pull request by MKuckert**
Fix for #18 

This ensures that `TaskCreationOptions.RunContinuationsAsynchronously` is passed to every `TaskCompletionSource` to ensure the completion is not running on the databases background thread.

Also simplifies all async wrappers by centralizing creation of the `TaskCompletionSource` into `Enqueue`

### CODE REVIEW

File: litedbasync/LiteDatabaseAsync.cs [hunk 1]
```diff
@@ -132,13 +132,15 @@ private void BackgroundLoop()
             }
         }
 
-        internal void Enqueue<T>(TaskCompletionSource<T> tcs, LiteAsyncDelegate function)
+        internal Task<T> Enqueue<T>(LiteAsyncDelegate<T> function)
```
Comment (mlockett42) [inline litedbasync/LiteDatabaseAsync.cs]: Please rename this function EnqueueAsync

File: litedbasync/LiteDatabaseAsync.cs [hunk 2]
```diff
@@ -357,7 +329,10 @@ protected virtual void Dispose(bool disposing)
                     _shouldTerminate.Cancel();
                     
                     // give the thread 5 seconds to exit... must not block forever here
-                    _backgroundThread.Join(TimeSpan.FromSeconds(5));
+                    if (!_backgroundThread.Join(TimeSpan.FromSeconds(5)))
+                    {
+                        var tooslow = true;
```
Comment (mlockett42) [inline litedbasync/LiteDatabaseAsync.cs]: the tooslow variable is unused. If you are going to use it it should be in camelCase eg tooSlow

**Review by mlockett42 — CHANGES_REQUESTED** [review]
Please also add yourself to the AUTHORS.TXT file. You should remerge from the target branch into yours, I find change it's location to the correct one.

**Comment by MKuckert** [comment]
> Please also add yourself to the AUTHORS.TXT file. You should remerge from the target branch into yours, I find change it's location to the correct one.

Have rebased onto `incoming` and added myself

File: litedbasync/LiteDatabaseAsync.cs (hunk 1 above)
Comment (MKuckert) [reply litedbasync/LiteDatabaseAsync.cs]: Done

File: litedbasync/LiteDatabaseAsync.cs (hunk 2 above)
Comment (MKuckert) [reply litedbasync/LiteDatabaseAsync.cs]: Removed the variable
